def DNA_strand(dna):
    listSeq = list(dna)
    listSeq.reverse()
    output = ''
    for base in listSeq:
        if base == "A":
            output += "T"
        if base == "T":
            output += "A"
        if base == "C":
            output += "G"
        if base == "G":
            output += "C"
    return output

str1 = 'AGAATTCTGCACCTCGGAGGTGTGCCCATTGTAAACATGGTGGAATCTACAATAAAGCCGATAACCCTGGTAATTCGAGTGCCAATAACGAGGCGATCCTCCTTTGGAACGGCTCGAACGAACTCAACTTGTCAATCTTTGTCCACTGCGGCCAAGTTAATCGCAGCATGGACATCGTAATATGCGCGGGGTCGATTACCCCTTAATTTTTTCACGTAACGGGGCCAGTTAGCTTCAAGCAGGGGACACACACTATGGCGGAACTCTGGAGCGCCTACGGGGGTTGGTTGGAGAGTGCGCATTGTAGATTACGGCTGAACCTCCTTACGCCAAGGGCCCCGTGAGCCCCTCGATAACGGCGCGTTCGTCTAGCCCCACCCAAATACAGCCTGCGCGAAGAACTGATGTCGTTTACGACACAATGAACCAATCTCATAATGGAATAGACCGGTCACGCGAATTCCGCAATTCCCAACTCGTTTGCAGTCACGACCGAGAACTAAGCCCGTCGTCTGTTTCCGCAGGCTTCGAACCGGTCAGCCACGTTCCTGTGCTAGCTATATCTGCATTATACCGCAATCCGCCTTCTACCGGCGGGTGACGTTACCCATACAAGCAGCTAGCGCCAAACACTGGACTACGTACGGCTGCAGAGTTTGTGTCCCGATGGACGCTATTAGATTTCTGAGCATCGCAGGCGATTTACTTCCAACACTTGACAGACCATATTTACTGATAGCGCTACCGACTTTCCCACACTTCGAGCGCGTAGATGCACTGATATCCTCTCTGGTAAAGTAGAGCTTACAACGACCGGGGG'

print(DNA_strand(str1))